name: java C22 with Maven

on:
    push:
      branches: [ 'main', 'dev', 'prod-support']
    pull_request:
        branches: ['main,' 'dev', 'prod-support']


jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
        java-version: 21
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify


